
# ****************************** Main settings ***************************************************
#_____________________________________________________________________________________________________________

# Название созданного VM
created_vm_name: my_created

# Скачанный VM file
downloaded_vm: C:\Users\taima\PycharmProjects\vm_changer\temp\downloaded\modifiedVMX.vmx

# Папка для сохранения измененного VM file
saved_vm: C:\Users\taima\PycharmProjects\vm_changer\temp\saved

# Количество итераций
iter_count: 3

# 1, 2, 3, 4
mac_generation_type: 1
#_____________________________________________________________________________________________________________

# ****************************** Add settings ******************************************
#_____________________________________________________________________________________________________________

disk_size_from: 40
disk_size_to: 1024
windows_path: C:\1china.iso